apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test-deployment
  labels:
    app: java-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec:
      containers:
      - name: java-test
        image: lurubino/test-repotest:latest
        ports:
        - containerPort: 8080
